### ISSUE TITLE
The repo should not contain a RI

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-health#10]
In MicroProfile, there is no RI concept. Everyone is free to provide an implementation. There is no category of RI or non RI. If the implementation is open source, you can put the url in the spec.

**Comment by heiko-braun** [comment]
To me a reference implementation is simply a reference to verify that the API is implementable and the develop the TCK. Nothing less, nothing more. Maybe our definition (and expectations) of an RI is different?

**Comment by kwsutter** [comment]
Maybe we should just call these "sample implementations"?  I know we had a
similar discussion with Config.  Besides the vendor solutions to the API,
providing a "sample implementation" to prove that it's implementable is a
good idea.  Due to the JCP process, I think the term "reference
implementation" has major implications and we should stay away from that
term.

**Comment by heiko-braun** [comment]
Sounds good.
