### ISSUE TITLE
Discuss HealthCheckResponse evolution for liveness and readiness

### ISSUE THREAD

**Issue by antoinesd** [eclipse/microprofile-health#143]

**Comment by derekm** [comment]
Since `@Health` checks cannot safely be assumed to be valid `@Liveness` checks, `@Health` checks should not automatically appear under `/health/live` (or `/health/liveness`).

I've stated in my review of the liveness/readiness PR that `/health` should contain only `@Health` checks, but I'm not 100% sure about that. Is there harm in `/health` showing all health, liveness and readiness checks?

Liveness and readiness status code behaviors seem to necessitate their own routes and their segregation from other health checks that only indicate survivable, degraded operation, but does also including the liveness and readiness failures in `/health` really pollute `/health`'s response? Maybe it doesn't...
