### ISSUE TITLE
DefaultConfigTest and ConfigTest Readiness TCKs have no expected or installed health procedures, but overall status DOWN?

### ISSUE THREAD

**Issue by pgunapal** [eclipse/microprofile-health#269]
A bit of confusion on the TCK and the spec doc:

From the spec, it says the following (https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/protocol-wireformat.adoc#health-check-procedures):

> - A producer with no liveness procedures expected or installed MUST return positive overall status (i.e. HTTP 200)
> - **A producer with no readiness procedures expected or installed MUST return positive overall status (i.e. HTTP 200)**
> - A producer with liveness procedures expected but not yet installed MUST return positive overall status (i.e. HTTP 200)
> - **A producer with readiness procedures expected but not yet installed MUST return negative overall status (i.e. HTTP 503)**

Since, the TCKs doesn't have any deployments, shouldn't the overall Readiness status return UP (HTTP 200), according to the second bullet, regardless if the config property is set or not?

From the last bullet, we should only return a negative overall Readiness status, if there are any Readiness procedures that are expected, but not yet installed/started.

From the [Empty default readiness health check responses](https://github.com/eclipse/microprofile-health/blob/master/spec/src/main/asciidoc/protocol-wireformat.adoc#empty-default-readiness-health-check-responses) section, it states that the MP Config property can be used when there are multiple deployments which have procedures expected, but some have not yet been processed/installed yet.

Unless, our intent was to change the overall default Readiness status to be DOWN, regardless of deployments with expected/installed Readiness procedures or not, we should clarify the second bullet from above, to reflect that?

Or, if our intent was to use the MP Config property for only multiple deployments in app servers, where users can set the default Readiness status to be UP, we should update the DefaultConfigTest and ConfigTest TCKs to test that scenario?

**Comment by xstefank** [comment]
Good catch. The issue was that I was unable to configure manual/unmanaged deployment in the TCK so I was unable to catch the deployment phase. I'm not sure whether other implementations can catch expected procedures beforehand but we should stick to the specification document. For now, I would remove DefaultConfigTest and leave only ConfigTest.

Thinking more about this, we can even have DefaultConfigTest as there may be runtimes that will reject any traffic before the readiness checks are processed. We can only test the scenario with the config property set. Thanks @pgunapal.

**Comment by xstefank** [comment]
Just to clarify:

* there is a single deployment in every test. Otherwise, arquillian wouldn't run.
* however, the deployment doesn't container any health checks. But this is something the container/runtime can't know before the deployment is processed.
* However, we can't know whether the container/runtime responds before processing the deployment (implicit expectation of the new tests) so in this sense, if the container manages deployment phase for readiness probe as `404...404...{processed-deployment-response}` and not in `404...{empty-checks-response}...{processed-deployment-response}` the test won't pass.

So if can't do unmanaged deployment (I will try once more) then these tests cannot be included because we can't predict whether empty check response is passed to the client.

**Comment by xstefank** [comment]
@pgunapal so even DefaultConfigTest makes sense with the above reasoning. Do you agree?

Even for multi deployment application servers, the server should expect some user-defined checks if there is a deployment present when the server is starting and thus negative response should be returned.

The only case where the positive response can be returned from readiness probe is when *application server is starting without any deployments* then you can expect that you don't have any user procedures defined.

**Comment by xstefank** [comment]
Ok, the tests are wrong because we can't even with unmanaged deployment catch the deployment phase unfortunately. I will revert them. Thanks for spotting this.
