### ISSUE TITLE
Default context for performing checks

### ISSUE THREAD

**Issue by rlcundiff** [eclipse/microprofile-health#48]
In the Protocol Mappings section of the spec document it says, "Producers SHOULD define a well known default context to perform checks"

What exactly does this mean?  If the runtime is handling the /health endpoint and invoking the HealthChecks in an installed app, what context could this be?

**Comment by starksm64** [comment]
I think what we are getting at here is that /health has a configurable element in the underlying runtime to deal with the configuration of the security requirements. For servlet based containers this would be a context associated with some web app deployment.

**Comment by heiko-braun** [comment]
See #45 that discussion should anser your question

**Comment by heiko-braun** [comment]
@rlcundiff I would prefer to close this issue in favour of the discussion at #45. Please let me know if this works for you.

**Comment by heiko-braun** [comment]
The `TCKConfiguration` uses a single URL for all tests. Is there anything else we can or should do to verify the requirement for a single, top level `/health` entrypoint? 

One thing I can think of is change the `TCKConfiguration` to only supply the host and port. This way we could enforce a specific web context to all tests.

@starksm64 Thoughts?

**Comment by johnament** [comment]
+1 to just supplying host/port and making the TCK add `/health`.  This is actually related to another issue I have, Hammock typically uses a random port for testing so the approach of using a system property is not ideal.

One thought.  We could ask each implementor to supply a `HealthTCKConfiguration` object with the host and port provided in there.  Then using Arquillian you can just do  `@ArquillianResource HealthTCKConfiguration config` rather than system properties.

I should be able to whip up a simple prototype this evening.
