### ISSUE TITLE
Re-introduce @Health qualifier to discover health check procedures 

### ISSUE THREAD

**Issue by heiko-braun** [eclipse/microprofile-health#53]
Slightly related to #36, but more general, I propose to bring back the `@Health` qualifier annotation and make it mandatory for discovery of `HealthCheck`'s in CDI contexts, i.e.:

```
@Health
@ApplicationScoped
public class SuccessfulCheck implements HealthCheck {
    @Override
    public Response call() {
        return Response.named("successful-check").up();
    }
}
```

#36 takes it further and talks about supporting the same qualifier on method level bindings, as in 

```
@ApplicationScoped
public class SomeBean  {

    @Health
    public Response call() {
        return Response.named("some-check").up();
    }
}
```

I'd recommend to include support for class level `@Health` qualifiers in 1.0 (this issue) and move method level `@Health` qualifiers to 1.1 (issue #36)

**Comment by heiko-braun** [comment]
Somewhat related is @jmesnil idea to leverage `@Health` for additional meta-data (see #34) that we may find useful as the spec evolves. But for now I'f keep it simple and just add the `@Health` annotation without attributes.

**Comment by johnament** [comment]
I like the second option - method level.  This makes it clearer what methods are meant to be health checks.  HOwever, then it would not be a qualifier but just an indicator that this method is a check.

**Comment by johnament** [comment]
errr.?

**Comment by heiko-braun** [comment]
@johnament no need to re-open. this issue is about `@Health` on the type level, which we support. Your comment about about method level indicators, will be addressed in #36 (scheduled for 1.1)

**Comment by johnament** [comment]
I reopened this because the ask here makes no sense.  Due to this change we now have belts and suspenders for health checks.  You need to both implement an interface and have an annotation (not even a qualifier!)

**Comment by johnament** [comment]
I've raised a PR that demonstrates my concerns with the annotation.  I don't have a problem with using it per se, however Hammock uses a very simple approach for finding health checks.  I don't want to complicate it further, and I also don't want to deviate too far from the CDI programming model, making it more confusing for users.

So here's my proposal - we use `@Health` but we actually make it a qualifier, so that it works with CDI as well.

One caveat, when we introduce secured health checks, it can't be a boolean.  Instead it should be an enum to allow proper look up.

**Comment by heiko-braun** [comment]
@johnament  Can you move your comment about security to #47?
