### ISSUE TITLE
Revisit the case of no procedures installed

### ISSUE THREAD

**Issue by heiko-braun** [eclipse/microprofile-health#75]
My concerns with the current approach to $subject:
- A GET request with no body isnt really Restful
- Empty body response, will clash with the future security approaches we discussed

I am therefore suggesting to change the $subject case, to include payload in the following form:

```
{
  "outcome": "UP",
  "checks": []
}
```

**Comment by heiko-braun** [comment]
@johnament @starksm64 any objections?

**Comment by johnament** [comment]
Well, right now the issue is that you're getting a 200 OK when there's no body.  This is what it looks like in Hammock:

```java
        if (healthCheckModel.getOutcome().equalsIgnoreCase(HealthCheckResponse.State.UP.name())) {
            resp.setStatus(200);
        } else {
            resp.setStatus(503);
        }
        if (!healthCheckModel.getChecks().isEmpty()) {
            jsonb.toJson(healthCheckModel, resp.getOutputStream());
        }
```
(yes I'm using a really simple servlet).

I personally preferred the 204 - no content result when there were no health checks, it made it clear that there's something wrong (in fact, in some clouds you can choose that this means the server's down).

If we want there to be a body when no checks are discovered, I would actually think a response of `200 - OK` with body `{"outcome":"UNKNOWN"}` would be more beneficial.

**Comment by heiko-braun** [comment]
@johnament per spec, with no procedures installed, the outcome is always `UP`. In addition to this the spec requires the inner protocol elements (i.e. JSON payload information) to be consistent with the outer one (i.e. HTTP status codes). This means outermost `200` and innermost `{"outcome":"UNKNOWN"}` is inconsistent.

**Comment by heiko-braun** [comment]
> I personally preferred the 204 - no content result when there were no health checks, it made it clear that there's something wrong (in fact, in some clouds you can choose that this means the server's down).

yes, that was the most cleanest, but apparently it didn't work with cloud foundry health checks.
